# docker build -f Dockerfile -t mediawiki_git_wget .
# docker run -it -v `pwd`:/scratch --rm mediawiki_git_wget:latest /bin/bash

FROM mediawiki:latest

RUN apt-get update && apt-get install -y \
    vim unzip libzip-dev git wget

RUN docker-php-ext-install zip

WORKDIR /opt

# downloaded from https://github.com/composer/composer/releases/tag/1.10.19
RUN wget https://github.com/composer/composer/releases/download/1.10.19/composer.phar

# https://stackoverflow.com/a/39802804/1164295
# https://getcomposer.org/doc/05-repositories.md#path
COPY composer.json /opt

COPY SemanticMediaWiki_3.2.2.zip \
     ParamProcessor_1.3.2.zip \
     http-request_1.3.0.zip \
     event-dispatcher_1.1.0.zip \
     callback-container_2.0.0.zip \
     ParserHooks_1.6.1.zip \
     json-schema_5.2.10.zip \
     elasticsearch-php_v7.10.0.zip \
     /opt/


# https://packagist.org/packages/mediawiki/semantic-media-wiki
# links to https://github.com/SemanticMediaWiki/SemanticMediaWiki/releases/tag/3.2.2
#RUN unzip SemanticMediaWiki_3.2.2.zip

# https://github.com/JeroenDeDauw/ParamProcessor/releases/tag/1.3.2
#RUN unzip ParamProcessor_1.3.2.zip

# https://packagist.org/packages/onoi/http-request
# https://github.com/onoi/http-request/releases/tag/1.3.0
#RUN unzip http-request_1.3.0.zip

# https://packagist.org/packages/onoi/event-dispatcher
# https://github.com/onoi/event-dispatcher/releases/tag/1.1.0
#RUN unzip event-dispatcher_1.1.0.zip

# https://packagist.org/packages/onoi/callback-container
# https://github.com/onoi/callback-container/releases/tag/2.0.0
#RUN unzip callback-container_2.0.0.zip

# https://packagist.org/packages/mediawiki/parser-hooks
# https://github.com/JeroenDeDauw/ParserHooks/releases/tag/1.6.1
#RUN unzip ParserHooks_1.6.1.zip

# https://packagist.org/packages/justinrainbow/json-schema
# https://github.com/justinrainbow/json-schema/releases/tag/5.2.10
#RUN unzip json-schema_5.2.10.zip

# https://packagist.org/packages/elasticsearch/elasticsearch
# https://github.com/elastic/elasticsearch-php/releases/tag/v7.10.0
#RUN unzip elasticsearch-php_v7.10.0.zip
