FROM mediawiki:1.31
# version pinned to 1.31 to match IFR script


RUN apt-get update && apt-get install -y \
    git vim unzip libzip-dev wget

RUN docker-php-ext-install zip

COPY ifr.tar /opt
WORKDIR /opt
RUN tar xvf ifr.tar
